### PR TITLE
Created spacy & gpt based text extractor

### PR DESCRIPTION
**Pull request by Umer-c**
Hi,
This is the text extractor part.

### CODE REVIEW

**Comment by rmeijden** [comment]
edit text: Added Spacy GPT text extractor for keywords

**Review by rmeijden — CHANGES_REQUESTED** [review]
edit text: Added Spacy GPT text extractor for keywords

**Review by Umer-c — COMMENTED** [review]
Nothing to change on the code level.

**Review by rmeijden — APPROVED** [review]
ok

**Pull request merged**
